language: node_js
node_js:
 - "lts/*"
addons:
  firefox: latest
before_install:
  - "cd speedway-web-administration-client"
install:
  - "npm install"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - "ng build"
  - "./node_modules/.bin/karma start --browsers Firefox --single-run"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
